services:
  front-end:
    build:
      context: .
      dockerfile: docker-go-js/frontendDockerfile
  back-end:
    build:
      context: .
      dockerfile: docker-go-js/backendDockerfile
    ports:
      - "9000:9000"
    depends_on:
      - front-end
