name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  golangci:
    runs-on: macos-latest
    name: lint
    defaults:
      run:
        working-directory: ./echo-go-gorm
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: false
      - name: Run linters
        run: gofmt -s -w .
