name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    runs-on: ubuntu-latest
    name: lint
    defaults:
      run:
        working-directory: ./echo-go-gorm
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: false
      - name: golangci-lint
        run: golangci-lint run
        with:
          version: v1.29
